version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8084:80"
        depends_on:
            - app
        container_name: app_to_do2_nginx

    app:
        build:
            context: .
            dockerfile: ./_docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - db
        container_name: to_do2_app

    db:
        image: mysql:8.0
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: my_db_application
            MYSQL_ROOT_PASSWORD: root

        ports:
            - "8103:3306"
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: to_do2_db
